FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . ./
CMD ["python", "-m", "aml_federated_training.train_federated", "--data-config", "config/data_config.yaml", "--model-config", "config/model_config.yaml", "--federated-config", "config/federated_config.yaml"]
